services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    # volumes:
    #   - .:/workspace
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true
